package io.github.depguard;

import java.io.File;
import java.io.FileReader;
import java.io.Reader;
import java.util.Properties;

import org.apache.maven.execution.MavenSession;
import org.apache.maven.model.Model;
import org.apache.maven.model.io.xpp3.MavenXpp3Reader;
import org.apache.maven.plugin.testing.AbstractMojoTestCase;
import org.apache.maven.project.MavenProject;
import org.apache.maven.repository.internal.MavenRepositorySystemUtils;
import org.eclipse.aether.DefaultRepositorySystemSession;
import org.eclipse.aether.RepositorySystem;
import org.eclipse.aether.internal.impl.SimpleLocalRepositoryManagerFactory;
import org.eclipse.aether.repository.LocalRepository;

/**
 * Base class for the dep-guard integration tests. Each test project under
 * {@code src/test/resources/it} resolves its dependencies from the synthetic local repository
 * generated by {@link TestRepositoryBuilder}; no network access is involved.
 */
public abstract class AbstractDepGuardMojoTestCase extends AbstractMojoTestCase
{
    private RepositorySystem repositorySystem;

    @Override
    protected void setUp()
        throws Exception
    {
        super.setUp();
        File repoDir = new File( getBasedir(), "target/test-repo" );
        TestRepositoryBuilder.build( repoDir );
        repositorySystem = MavenRepositorySystemUtils.newServiceLocator().getService( RepositorySystem.class );
        assertNotNull( repositorySystem );
    }

    protected MavenProject readProject( String dirName )
        throws Exception
    {
        File pom = new File( getBasedir(), "src/test/resources/it/" + dirName + "/pom.xml" );
        assertTrue( "test project pom exists: " + pom, pom.isFile() );
        Model model;
        Reader reader = new FileReader( pom );
        try
        {
            model = new MavenXpp3Reader().read( reader );
        }
        finally
        {
            reader.close();
        }
        MavenProject project = new MavenProject( model );
        project.setFile( pom );
        return project;
    }

    protected MavenSession newTestSession( MavenProject project )
        throws Exception
    {
        MavenSession session = newMavenSession( project );
        DefaultRepositorySystemSession repoSession =
            (DefaultRepositorySystemSession) session.getRepositorySession();
        File repoDir = new File( getBasedir(), "target/test-repo" );
        repoSession.setLocalRepositoryManager( new SimpleLocalRepositoryManagerFactory()
            .newInstance( repoSession, new LocalRepository( repoDir ) ) );
        if ( session.getRequest().getSystemProperties() == null )
        {
            session.getRequest().setSystemProperties( new Properties() );
        }
        if ( session.getRequest().getUserProperties() == null )
        {
            session.getRequest().setUserProperties( new Properties() );
        }
        return session;
    }

    protected CheckMojo lookupCheckMojo( String dirName )
        throws Exception
    {
        MavenProject project = readProject( dirName );
        MavenSession session = newTestSession( project );
        CheckMojo mojo = (CheckMojo) lookupConfiguredMojo( session, newMojoExecution( "check" ) );
        mojo.setRepositorySystem( repositorySystem );
        return mojo;
    }

    protected TreeMojo lookupTreeMojo( String dirName )
        throws Exception
    {
        MavenProject project = readProject( dirName );
        MavenSession session = newTestSession( project );
        TreeMojo mojo = (TreeMojo) lookupConfiguredMojo( session, newMojoExecution( "tree" ) );
        mojo.setRepositorySystem( repositorySystem );
        return mojo;
    }

    protected String readReport( String dirName, String fileName )
        throws Exception
    {
        File file = new File( getBasedir(),
            "src/test/resources/it/" + dirName + "/target/dep-guard/" + fileName );
        assertTrue( "report exists: " + file, file.isFile() );
        StringBuilder sb = new StringBuilder();
        Reader reader = new FileReader( file );
        try
        {
            char[] buffer = new char[4096];
            int read;
            while ( ( read = reader.read( buffer ) ) >= 0 )
            {
                sb.append( buffer, 0, read );
            }
        }
        finally
        {
            reader.close();
        }
        return sb.toString();
    }
}
